export const communityUrl = "https://www.linkedin.com/groups/14571141/";
export const hostLinkedInUrl = "https://www.linkedin.com/in/sungmikim77/";
export const interviewUrl = "https://microsoft.github.io/mwkorea/monthlycopilot/MonthlyCopilotInterviewKimSM/";

export const seasonOneEvents = [
  { slug: "ignite-after-party", number: "01", date: "2024.11.30", label: "SPECIAL", title: "Microsoft Ignite After Party with MVP", summary: "Ignite의 핵심 발표를 함께 읽고, MVP와 직접 듣고 만들며 시작한 AI놀이터의 첫 공식 기록입니다.", image: "/season1/01-ignite-after-party.png", tags: ["Ignite", "MVP", "Hands-on"], detail: "커뮤니티의 힘, 피아노 앱 핸즈온, Power Apps·Dynamics 365·RAG·SLM·Semantic Kernel까지 하루 동안 촘촘하게 나눴습니다.", results: ["Microsoft MVP 리드 이소영님의 커뮤니티 키노트로 시작", "피아노 앱 핸즈온과 합주를 통해 기술을 함께 만드는 경험으로 전환", "Power Apps·Dynamics 365부터 RAG·SLM·Semantic Kernel까지 Ignite 발표를 한국 현장 관점으로 재해석"], feedback: "‘다른 사람의 성공에 기여하고 있는가?’라는 질문이 기술 발표를 넘어, AI놀이터가 지향할 커뮤니티의 기준점으로 남았습니다.", sources: [{ label: "행사 시작과 키노트 기록", url: "https://www.linkedin.com/posts/sungmikim77_microsoft-ignite-2024-after-party-with-activity-7267528748801880064-p6vo" }] },
  { slug: "summer-meetup", number: "02", date: "2025.06.22", label: "SUMMER", title: "AI 동료와 함께 살아갈 준비", summary: "사례로 이해하는 AI와 노코드로 구현하는 AI, 두 트랙으로 AI 에이전트와 일하는 법을 탐색했습니다.", image: "/season1/02-summer-meetup.png", tags: ["AI Agent", "No-code", "Case Study"], detail: "CHATDA, AI 투자 에이전트, Copilot과 리더십, AI 프로젝트 관리 프레임워크 등 현업 사례를 한 자리에서 나눴습니다.", results: ["AI 기초 60명·No Code 50명 규모의 두 트랙으로 설계", "식전 피아노 앱 핸즈온과 Power Platform 합주로 참여형 시작", "AI 에이전트 시대의 비즈니스 앱, 로우코드 서비스화, Copilot Studio 신기능을 실무 사례로 연결"], feedback: "등록 좌석이 빠르게 소진될 만큼 AI Agent와 No Code에 대한 관심이 컸습니다. 연사들은 기술뿐 아니라 조직 운영·평가·책임 있는 AI까지 함께 고민하는 자리였다고 정리했습니다.", sources: [{ label: "AI·No Code 트랙 안내", url: "https://kr.linkedin.com/posts/leejaeseok_ai-%EB%86%80%EC%9D%B4%ED%84%B0-622%EC%9D%BC-microsoft-ai-user-community-activity-7337033309257965570-EyPZ" }, { label: "프런티어 기업 세션 소개", url: "https://kr.linkedin.com/posts/yoondavid_ai-%EB%86%80%EC%9D%B4%ED%84%B0-622%EC%9D%BC-microsoft-ai-user-community-activity-7338008986660589569-f3Xy" }] },
  { slug: "fall-meetup", number: "03", date: "2025.09.27", label: "FALL", title: "What’s Your Dream?", summary: "세상의 문제를 푸는 스타트업에게 배우며, 각자의 꿈을 AI와 어떻게 현실로 만들지 질문한 가을 밋업입니다.", image: "/season1/03-fall-meetup.png", tags: ["Startup", "Agentic AI", "Vibe Coding"], detail: "Agentic AI와 데이터 혁신, VC와 스타트업, 바이브 코딩 이야기에 영상 메시지와 도서 기부가 더해졌습니다.", results: ["Microsoft·VC·Bio·Event·Beauty·Survey·AI Service·Tech 현장의 8개 관점을 한 무대에 연결", "Simon Squibb의 영상 메시지와 도서 후원으로 ‘꿈을 실행하는 질문’을 확장", "Agentic AI, 스마트 클리닉, 디지털 이벤트, 전 직원 바이브코딩 등 실제 스타트업 실행 사례 공유"], feedback: "연사 이보라님은 현실적인 바이브코딩 경험을 나눈 뒤 ‘많이 배웠습니다’라고 회고했습니다. 주최 기록에서도 스타트업 리더와 영상 메시지가 연속적인 영감을 주었다고 정리했습니다.", sources: [{ label: "연사 후기와 전체 아젠다", url: "https://kr.linkedin.com/posts/learner-bora_ai-%EB%86%80%EC%9D%B4%ED%84%B0-927%ED%86%A0-microsoft-ai-community-activity-7377682691019882496-gNl7" }, { label: "행사 결과·연사·후원 기록", url: "https://kr.linkedin.com/posts/ht-hwang_%EC%97%94%ED%84%B0%ED%94%84%EB%9D%BC%EC%9D%B4%EC%A6%88%EA%B3%B5%EA%B3%B5%EA%B8%B0%EA%B4%80%EC%9D%98-ax%EB%A5%BC-%EB%8F%95%EB%8A%94-ax-%ED%8C%8C%EC%9A%B4%EB%93%9C%EB%A6%AC-ax-%ED%8C%8C%EC%9A%B4%EB%93%9C%EB%A6%AC%EB%A5%BC-activity-7379373307332190208-AhOR" }] },
  { slug: "winter-meetup", number: "04", date: "2026.01.18", label: "WINTER", title: "슬기로운 AI 생활", summary: "워크와 라이프에서 AI를 현명하게 쓰는 법과 Excel부터 데이터 플랫폼까지 실무 활용 팁을 모은 피날레입니다.", image: "/season1/04-winter-meetup.png", tags: ["Copilot", "Data", "Excel"], detail: "AI 시대의 성장, MVP들의 실전 노하우, 데이터 기반 업무와 Agentic AI까지 바로 적용할 수 있는 팁을 공유했습니다.", results: ["Copilot을 업무 비서에서 함께 일하는 동료인 Agent로 확장", "Researcher·Analyst 등 미리 빌드된 에이전트와 나만의 제품 안내 에이전트 제작 흐름 공유", "MVP 재능기부와 Microsoft 운영진이 함께 만든 AI·Data 실무 커뮤니티 피날레"], feedback: "참가자 백은경님은 MVP들의 재능기부와 Microsoft 직원들의 준비가 모인 ‘후끈한 커뮤니티 한마당’이었다며 ‘많이 배우고 갑니다’라고 남겼습니다.", sources: [{ label: "Agent 세션 상세 기록", url: "https://kr.linkedin.com/in/canrobot" }, { label: "참가자 현장 후기", url: "https://kr.linkedin.com/in/kate-baek-lovecat-blog" }] },
];

export const seasonTwoEvents = [
  { slug: "build", state: "ARCHIVE", eyebrow: "OFFICIAL EVENT · BUILD", title: "아이디어를 실제 결과로 만드는 빌드 행사", description: "AI와 함께 문제를 정의하고, 팀으로 빠르게 만들고, 결과를 공유한 시즌 2의 첫 공식 행사입니다.", accent: "blue" },
  { slug: "snowflake", state: "NOW", eyebrow: "OFFICIAL EVENT · SNOWFLAKE", title: "Snowflake와 함께 데이터에서 가능성을 발견합니다", description: "데이터와 AI가 만나는 최신 현장을 배우고 직접 연결해보는 시즌 2의 다음 공식 행사입니다.", accent: "cyan" },
];

export const teams = [
  { no: "01", name: "PLAY", lead: "문종훈", sub: "TBU", purpose: "사람을 모으고 연결합니다.", roles: ["Crew 온보딩", "멤버 소통과 참여", "네트워킹 운영", "현장 지원"] },
  { no: "02", name: "SHARE", lead: "윤미영", sub: "허석 · 박현정", purpose: "콘텐츠를 만들고 나눕니다.", roles: ["LinkedIn 콘텐츠", "홍보·스폰서 협력", "학습 기록", "주제·리더 발굴"] },
  { no: "03", name: "BUILD", lead: "전대호", sub: "진미나", purpose: "경험을 만들고 누적합니다.", roles: ["공식 Meetup 실행", "Venue·운영", "행사 기록", "경험 아카이빙"] },
];
